### ISSUE TITLE
Create a crud website.

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/WebDev#10]
Rules: https://github.com/shubham7668/WebDev#rules

**Comment by Rish-it** [comment]
Hi sir !!! I want to add my contribution to this project as a part of hacktoberfest

**Comment by SharmilaChoudhary** [comment]
hey @shubham7668 I would like to work on this issue please assign it me.

**Comment by shubham7668** [comment]
> hey @shubham7668 I would like to work on this issue please assign it me.

Done 
Project should be unique 
And make sure to read rules before creating a pr
