### ISSUE TITLE
Create a Random size/color rectangle generator 

### ISSUE THREAD

**Issue by shubham7668** [shubham7668/WebDev#15]
Make sure to follow all rules
github.com/shubham7668/WebDev#rules

**Comment by mayank-del** [comment]
@shubham7668 ,I have read the rules, Can  I add my project?

**Comment by shubham7668** [comment]
Yes go ahead

> @shubham7668 ,I have read the rules, Can I add my project?

**Comment by Rish-it** [comment]
I have read the rules and I want to contribute to this project as a Part of hacktoberfest
add me as a contributor .

**Comment by shubham7668** [comment]
Hey @Rish-it this issue is already fulfilled(Only unique projects allowed)
Kindly create another issue if you want to contribute & mention me i will assign that for you

**Comment by mayank-del** [comment]
@shubham7668 sir ,please add hacktoberfest label ,else it will not be counted, my merged pr is not reflected yet in my profile, so , please add label of hacktoberfest

**Comment by shubham7668** [comment]
> @shubham7668 sir ,please add hacktoberfest label ,else it will not be counted, my merged pr is not reflected yet in my profile, so , please add label of hacktoberfest

Actually, it does not matter(in reflecting)
But i have added let see if it works
