### ISSUE TITLE
NOTE MAKER

### ISSUE THREAD

**Issue by ritviz344** [shubham7668/WebDev#20]
Hey @shubham7668 , I want add my note making website . Kindly assign this issue to me and considered this as my hacktoberfest2022 pr.
THANK YOU!

**Comment by shubham7668** [comment]
Hey @ritviz344 we arent accepting any pr till 13 oct.
Implementing more validation & checks till then 
So keep that in mind

**Comment by Harsh0326** [comment]
Hey @shubham7668  can you assign me ?

**Comment by shubham7668** [comment]
> Hey @shubham7668 can you assign me ?

its's done
