### ISSUE TITLE
Dark Theme switch system added

### ISSUE THREAD

**Issue by ElvinPero** [shubham7668/WebDev#36]
### Is your feature request related to a problem? Please describe
A dark mode is needed for almost all sites.

### Describe the solution you'd like
 I can make one which even has the ability to retain changes after refresh.

### Describe alternatives you've considered
Changes theme to dark.
ability to retain.

### Additional context**
Working on it

**Comment by ElvinPero** [comment]
@shubham7668 Assign this issue for me

**Comment by ElvinPero** [comment]
@shubham7668 I HAVE added the deploy link. You can merge under hacktoberfest-accepted

**Comment by shubham7668** [comment]
> @shubham7668 I HAVE added the deploy link. You can merge under hacktoberfest-accepted

done
