### ISSUE TITLE
Gallery Webpage

### ISSUE THREAD

**Issue by RaginaPhalangae** [shubham7668/WebDev#45]
I would like to add a Gallery webpage designed beautifully with the help of HTML, CSS, JS, and tools like Lightbox. Kindly assign me this issue; it will give a boost to my contributions to Hacktoberfest.

**Comment by shubham7668** [comment]
Go ahead @RaginaPhalangae

**Comment by RaginaPhalangae** [comment]
@shubham7668 Can you please add "Hacktoberfest accepted" label? It will be very kind of you and will certainly motivate me more to make a quality contribution.

**Comment by RaginaPhalangae** [comment]
@shubham7668 Thank you.

**Comment by Deepanshu1008** [comment]
can you assign this task to me?

**Comment by shubham7668** [comment]
> can you assign this task to me?

Go ahead @Deepanshu1008

**Comment by Deepanshu1008** [comment]
please help me i am a newbie

**Comment by shubham7668** [comment]
> please help me i am a newbie

What kind of help you needed

**Comment by Deepanshu1008** [comment]
i have added the file using fork

**Comment by Deepanshu1008** [comment]
please merge the pull request now

**Comment by shubham7668** [comment]
> please merge the pull request now

Create a valid pull request
You have to add your files in `projects` folder else it will be mess
And deploy your project and give me link
